
variables:
   workspace-name: 'ws-ml' # Workspace Service Connection name
   resourcegroup-name: 'RG-ML' # AML Resource Group name
   experiment-name: 'DevOpsExperiment' # AML Experiment name
   trainingcompute-name: 'mytrcompute44' # AML Compute cluster name
   trainingscript-name: 'test2.py' # Model training script name in repo
   datastore-name: 'myundatastore' # Datastore name
   dataset-name: 'iris.csv' # Dataset name residing in storageaccount
   #model-name: 'mynewmodel' # Model name
   aks-name: 'akscluster' # AKS cluster name
   aksservice-name: 'devopsservice' # AKS service name


trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'


steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install Python Tools'
- script: python -m pip install -r requirements.txt
  displayName: 'Install Dependencies'


- task: PythonScript@0
  displayName: 'Training Model'
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)/trainingexperiment.py'
    arguments: --ws=$(workspace-name) --rg=$(resourcegroup-name) --experiment=$(experiment-name) --trcompute=$(trainingcompute-name) --trainingscript=$(trainingscript-name) --datastore=$(datastore-name) --dataset=$(dataset-name)

- task: PythonScript@0
  displayName: 'Deploying Model'
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)/deployment.py'
    arguments: --ws=$(workspace-name) --rg=$(resourcegroup-name) --aksname=$(aks-name) --servicename=$(aksservice-name)
#yaml ended
